"""Initial schema

Revision ID: 4b0cd9cb2a54
Revises: 
Create Date: 2026-05-01 01:11:16.994200

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4b0cd9cb2a54'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eclipse_foundation_projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependency_track_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ef_project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ef_project_id'], ['eclipse_foundation_projects.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ef_project_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ef_project_id'], ['eclipse_foundation_projects.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('github_workloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('repo_owner', sa.String(), nullable=False),
    sa.Column('repo_owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['workloads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_name', 'repo_owner', 'repo_owner_id')
    )
    op.create_table('jenkins_workloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['workloads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jenkins_workloads')
    op.drop_table('github_workloads')
    op.drop_table('workloads')
    op.drop_table('dependency_track_projects')
    op.drop_table('eclipse_foundation_projects')
    # ### end Alembic commands ###
